---
- name: check for container that actually exist
  shell: 'docker ps -aq --filter "name={{ project | replace(" ", "-") }}-{{ deploy_environment }}"'
  register: found_containers

- name: remove containers found
  shell: 'docker stop {{ found_containers.stdout }} && docker rm -f {{ found_containers.stdout }}'
  when: found_containers.stdout

- name: start docker container
  command: 'docker run --name={{ project | replace(" ", "-") }}-{{ deploy_environment }} -d --restart=always {{ project | replace(" ", "-") }}:{{ deploy_environment }}'